FROM ubuntu:18.04
#####------------------------------
#####  python virtual environment
#####------------------------------
RUN apt update && apt install -y \
      software-properties-common \
      python3.7 \
      python3-pip
RUN add-apt-repository ppa:deadsnakes/ppa



