version: 2 
jobs:
  build:
#    machine: true
#    macos:  # macOS Executor を使用していることを示します
#      xcode: "10.0.0" # 選択された Xcode のバージョン
    machine:
      image: circleci/classic:edge
    working_directory: ~/middleware
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: build
          command: docker-compose -f middleware/docker-compose.yml up -d --build
      - run:
          name: stop
          command: docker-compose -f middleware/docker-compose.yml down
