version: 2 # CircleCI のバージョン 2.0 を使用していることを示します
jobs: # 1回の実行の基本作業単位
  build: # `Workflows` を使用しない実行では、エントリポイントとして `build` ジョブが必要です
    working_directory: ~/middleware
    machine: true
    macos:  # macOS Executor を使用していることを示します
      xcode: "10.0.0" # 選択された Xcode のバージョン
    steps: # 実行する一連のコマンド
      - checkout  # ユーザーのバージョン管理システムからコードをプルダウンします
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: check
          command: pwd
      - run:
          name: check
          command: ls
      - run:
          # Xcode の CLI ツール `xcodebuild` を使用してテストを実行します
          name: build
          command: docker-compose -f middleware/edocker-compose.yml up -d --build
      - run:
          # Xcode の CLI ツール `xcodebuild` を使用してテストを実行します
          name: stop
          command: docker-compose -f middleware/docker-compose.yml down
