version: '2'

services:
  science:
    build: jupyter
    ports:
      - "8285:8888"
    volumes:
      - ../software:/home/jovyan/notebook
    working_dir: "/home/jovyan/notebook/jupyter"
    command: jupyter notebook --ip=0.0.0.0 --allow-root --no-browser --NotebookApp.token=''

