version: '3'

services:
  science:
    build: jupyter
    ports:
      - "8285:8888"
    volumes:
      - ../software:/home/jovyan/notebook
    command: jupyter notebook --ip=0.0.0.0 --allow-root --no-browser --NotebookApp.token=''

  shell:
    build: shell
    depends_on:
      - python
    volumes: # shell x > ./shell o
      - ./shell/setting:/root
    working_dir: /root
    tty: true # コンテナがバックグラウンドで稼働し続ける (avoid stopping)

  python:
    build: python

