version: '3'

services:
  science:
    build: jupyter_setting
    depends_on:
      - jupyterbase
    ports:
      - "8285:8888"
    volumes:
      - ../software:/home/jovyan/notebook
    working_dir: /home/jovyan/notebook/jupyter
    command: jupyter notebook --ip=0.0.0.0 --allow-root --no-browser --NotebookApp.token=''

  shell:
    build: shell
    depends_on:
      - jupyterbase
    ports:
      - "5000:5000"
      - "3000:3000"
    volumes: # shell x > ./shell o
      - ../../setting:/home/jovyan
      - ../software:/home/jovyan/notebook
    working_dir: /home/jovyan/notebook/
    command: tmux
    tty: true # avoid container stopping

  jupyterbase:
    build: jupyter_python_module
